### PR TITLE
Added data methods to Polyhedron()

### PR DESCRIPTION
**Pull request by arpastrana**
### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.

### Checklist

1. [x] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).
1. [x] If you add new functions/classes, check that:
   1. [x] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

### PR Description

This first commit of the PR intends to solve issue #398 by implementing `to_data`, `from_data` methods; as well as the `data` property.

@gonzalocasas I was wondering though if we should check if `len(faces)` is one of the supported face count values: (4, 6, 8, 12, 20)?

### CODE REVIEW

**Comment by arpastrana** [comment]
I think we could do that with `cls.generate()`...

**Comment by tomvanmele** [comment]
could you remove the `to_data` function? want to get rid of them everywhere...

**Comment by arpastrana** [comment]
Sure! Just for curiosity, why would you like to get them removed everywhere?

**Comment by tomvanmele** [comment]
just a wrapper for `data` and i would like to go towards "1 correct/preferred way of doing things"

**Comment by gonzalocasas** [comment]
>>> could you remove the to_data function? want to get rid of them everywhere...

>> Sure! Just for curiosity, why would you like to get them removed everywhere?

> just a wrapper for data and i would like to go towards "1 correct/preferred way of doing things"

I would prefer to keep `to_data` for two reasons. 1) If there is a `from_data`, the "principle of least surprise" says there should be a complementary `to_data`. 2) consistency: the convention of `to_data`/ `from_data` is extremely spread, not only within compas, but on extension packages, getting rid of it partially will create inconsistency in the ecosystem.

So even if this is already merged, I would really suggest to re-add it.

**Pull request merged**
