### PR TITLE
new/modified mesh class methods

### PR DESCRIPTION
**Pull request by robin-oval**
new
mesh topology: is_empty, euler, genus
polyedge topology: boundaries
mesh geometry: area, centroid, normal

modified
edges_on_boundary with option to get them pointing outwards

### CODE REVIEW

**Comment by tomvanmele** [comment]
i like these additions very much.
however, i am trying to reduce the complexity and responsibilities of the mesh class on a separate development branch.
in that context, should these functions not be defined in a separate module rather then as part of the mesh class definition?

**Comment by robin-oval** [comment]
I agree that the original mesh module is growing too big. As they can be quite specific, would you suggest a mesh_topology and a mesh_geometry modules with mesh functions instead of methods?

**Comment by tomvanmele** [comment]
if you fetch the branch "reorganise_data_and_geo" you can see what i am working towards.

basically, i am making `compas.geometry`, `compas.topology`, `compas.numerical` completely independent. datastructure-related functionality will be accessible from `compas.datastructures`.  

in `compas.datastructures` the definition of a data structure should become leaner and the algorithmic stuff moved into separate modules.

usage would then be:

```python
from compas.datastructures import Mesh
from compas.datastructures import mesh_contours
from compas.datastructures import mesh_subdivide
from compas.datastructures import mesh_join
from compas.datastructures import mesh_...
```

**Comment by robin-oval** [comment]
I see. It will be much more intuitive indeed. 
Should I modify my PR according to the structure in the reorganise_data_and_geo branch or do I modify it once this structure is in master?
Or do I do this PR on the reorganise_data_and_geo branch?

**Comment by tomvanmele** [comment]
no, leave it as it is. we can fix later...

**Comment by robin-oval** [comment]
alright

**Comment by robin-oval** [comment]
are these okay for now then?

**Comment by tomvanmele** [comment]
cool, merged, thanks robin

**Pull request merged**
