### PR TITLE
Move data files

### PR DESCRIPTION
**Pull request by gonzalocasas**
Why do we keep struggling about this? Let's move data files into `src/compas/data` and have them shipped for the non-dev installs. This resolves a whole lot of little annoyances and differences between conda/pip installs vs dev installs.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gonzalocasas** [comment]
This is to be merged into `realpath` branch (or `main` after that one is merged). That's why the CI tests have not been triggered.

**Comment by tomvanmele** [comment]
sure, but perhaps we should then revise the selection of sample files and give them somewhat more descriptive names. the current set just randomly grew out of stuff i had on my computer at some point in time. especially if we want them to be really useful for examples and test they need to be curated a bit more carefully.

in addition, we then perhaps also need to add a location for slightly larger files. otherwise we will needlessly increase the size of the installable package...

**Comment by tomvanmele** [comment]
also, perhaps we could/should rename the `get` function...

**Comment by tomvanmele** [comment]
other than that, i am all for it!

**Comment by gonzalocasas** [comment]
> especially if we want them to be really useful for examples and test they need to be curated a bit more carefully.

They look relatively decent to me.. (except `butt_model.obj`, really hoping it's a butt joint model... 😛 )


> we then perhaps also need to add a location for slightly larger files

Good point. I realize I forgot to fix the `get` function, because now it would still try to load from `https://github.com/compas-dev/compas/raw/main/data/`, so what I could do is change `get` to 1) first check locally in the new location `src/data/samples`, if not found 2) go to the github repo, but not try to get them from `src/data/samples` of the repo, instead, maybe use `https://github.com/compas-dev/compas/raw/main/samples/` and we add a top-level dir for large(er) files.
Sounds good?



> also, perhaps we could/should rename the `get` function...

I actually got so used to `get` that now it feels odd to rename, but here are some alternatives, let me know if you like any?
- `compas.get_sample_path()`
- `compas.get_example_path()`
- `compas.sample_path()`
- `compas.get_sample()`
- `compas.get_example()`

or something else?

**Comment by tomvanmele** [comment]
> They look relatively decent to me.. (except `butt_model.obj`, really hoping it's a butt joint model... 😛 )

no unfortunately it is just a surface that looks like a but and was used to test bestfit algorithms...

**Comment by tomvanmele** [comment]
> Good point. I realize I forgot to fix the `get` function, because now it would still try to load from `https://github.com/compas-dev/compas/raw/main/data/`, so what I could do is change `get` to 1) first check locally in the new location `src/data/samples`, if not found 2) go to the github repo, but not try to get them from `src/data/samples` of the repo, instead, maybe use `https://github.com/compas-dev/compas/raw/main/samples/` and we add a top-level dir for large(er) files.
> Sounds good?

yup

**Comment by tomvanmele** [comment]
> I actually got so used to `get` that now it feels odd to rename, but here are some alternatives, let me know if you like any?

let's maybe leave that for compas 2.0 indeed :)

**Comment by gonzalocasas** [comment]
@brgcode better now?

**Review by tomvanmele — APPROVED** [review]
LGTM

**Pull request merged**
