### PR TITLE
Add Brep.from_loft for Rhino

### PR DESCRIPTION
**Pull request by gonzalocasas**
Added implementation for Rhino of the `Brep.from_loft` pluggable.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tomvanmele — APPROVED** [review]
LGTM

**Comment by tomvanmele** [comment]
> ## [Codecov](https://app.codecov.io/gh/compas-dev/compas/pull/1405?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev) Report
> 
> All modified and coverable lines are covered by tests ✅
> 
> > Project coverage is 60.69%. Comparing base [(`a26b7e3`)](https://app.codecov.io/gh/compas-dev/compas/commit/a26b7e3d65fb0483bfcaa910d51e0cd011409e33?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev) to head [(`fb6cba1`)](https://app.codecov.io/gh/compas-dev/compas/commit/fb6cba18caaffccd9a8af623ee1f257068b2c7dd?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev).
> 
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/compas-dev/compas/pull/1405?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev).

?!

**Comment by gonzalocasas** [comment]
> > ## [Codecov](https://app.codecov.io/gh/compas-dev/compas/pull/1405?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev) Report
> > All modified and coverable lines are covered by tests ✅
> > > Project coverage is 60.69%. Comparing base [(`a26b7e3`)](https://app.codecov.io/gh/compas-dev/compas/commit/a26b7e3d65fb0483bfcaa910d51e0cd011409e33?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev) to head [(`fb6cba1`)](https://app.codecov.io/gh/compas-dev/compas/commit/fb6cba18caaffccd9a8af623ee1f257068b2c7dd?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev).
> > 
> > 
> > Additional details and impacted files
> > [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/compas-dev/compas/pull/1405?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=compas-dev).
> 
> ?!

I guess the weird output is because we exclude `compas_rhino` from coverage, don't we?

**Comment by gonzalocasas** [comment]
@tomvanmele I tried to see how this would be implemented in OCC, but oh lord, occ is painful

**Comment by tomvanmele** [comment]
don't bother i already have this locally. i just need to find the time to put it in a PR...

**Pull request merged**
