### PR TITLE
Remove default __str__ implementation of data objects

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by beverlylytle** [comment]
A consequence of this is that subclasses of `Data` that don't have `__str__` or `__repr__` defined will be printed with Python's somewhat useless and unaesthetic default.  `Mesh` and `Network` are examples of this.  Is that desired?

**Review by gonzalocasas — APPROVED** [review]
LGTM!

**Comment by gonzalocasas** [comment]
> A consequence of this is that subclasses of `Data` that don't have `__str__` or `__repr__` defined will be printed with Python's somewhat useless and unaesthetic default. `Mesh` and `Network` are examples of this. Is that desired?

Yeah, that's true but currently all data objects print their data output which is rather annoying as a default, that's why we had to add `repr` in most examples of the workshops we did recently.  And big data structures should anyway default to something like `<Mesh at 0x0000127memorylocaltiona32662>`

**Comment by tomvanmele** [comment]
> A consequence of this is that subclasses of `Data` that don't have `__str__` or `__repr__` defined will be printed with Python's somewhat useless and unaesthetic default.  `Mesh` and `Network` are examples of this.  Is that desired?

no, indeed. but i think we perhaps need to resolve this by adding a meaningful repr to the data structures and even a print function that indicates with its name that it will be printing the data and not a representation of the object...

**Comment by beverlylytle** [comment]
> all data objects print their data output which is rather annoying as a default

Totally agree with this.

>  And big data structures should anyway default to something like <Mesh at 0x0000127memorylocaltiona32662>

They should?  Wouldn't it be nicer if it contained higher level information like the mesh's name and number of vertices?

**Comment by gonzalocasas** [comment]
> They should? Wouldn't it be nicer if it contained higher level information like the mesh's name and number of vertices?

You're right, `should` is not the correct word. They `could` and that would be enough. And agree with you, if they show any additional summary info, that'd be nice. The `RobotModel` does exactly what you say, it prints out a one-liner (eg `Robot name=abb_irb6640, Links=11, Joints=10 (6 configurable)`)

**Comment by tomvanmele** [comment]
> You're right, `should` is not the correct word. They `could` and that would be enough. And agree with you, if they show any additional summary info, that'd be nice. The `RobotModel` does exactly what you say, it prints out a one-liner (eg `Robot name=abb_irb6640, Links=11, Joints=10 (6 configurable)`)

with the mesh there is a "summary" method ```print(mesh.summary())```. it outputs something like this
```
Mesh
==========
- vertices: x
- faces: y
- edges: z
```
we could add an overview of the default vertex/edge/face attributes and the items stored in `attributes`?
and make sure that `__str__` returns this...

**Comment by gonzalocasas** [comment]
the content of `summary()` sound good for the `Mesh.__str__`. I would personally prefer it to be a one-liner in `__str__` (ie. `<Mesh of vertices: x, faces: y, edges: z>`).

**Review by beverlylytle — APPROVED** [review]
Looks good!

**Pull request merged**
