### PR TITLE
Transformations

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
this PR is more meant for discussion than anything else...

**Comment by tomvanmele** [comment]
the stl stuff was not meant to be part of this...

**Comment by tomvanmele** [comment]
the tests also need to be updated further for consistency.
for example using `allclose` everywhere.
the matrix methods could also benefit from a few more helper methods to make the implementations more transparent...

**Comment by tomvanmele** [comment]
something to consider is to write the matrix methods specifically for 4x4 matrices. they are not properly tested for anything else, so we should not encourage any other use...

**Comment by tomvanmele** [comment]
@romanarust @gonzalocasas ping

**Comment by tomvanmele** [comment]
shall i just finalise now and merge?

**Comment by romanarust** [comment]
Let me make a final check tomorrow, i‘ll ping u

**Comment by romanarust** [comment]
ok, i think i am done.. 
The only question i have: we now renamed all `Projection.from_*`, should we also rename `matrix_from_orthogonal_projection`, etc.?

**Comment by tomvanmele** [comment]
shall i resolve the conflict and merge?

**Pull request merged**
