### PR TITLE
Fix error in ghpython draw_mesh where an System.Array was expected

### PR DESCRIPTION
**Pull request by tetov**
### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- ~I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.~
- ~I have added tests that prove my fix is effective or that my feature works.~
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tetov** [comment]
SetColor with two arguments defaults to an overload that expects MeshFace, hence the four argument version.

I can't manage to display vertex colors in Rhino/Grasshopper though...

**Comment by tomvanmele** [comment]
@gonzalocasas @chenkasirer i can't provide reliable feedback when it comes to GHPython...

**Review by chenkasirer — APPROVED** [review]
LGTM.

**Comment by chenkasirer** [comment]
@tetov thanks for fixing this.
What do you mean you can't manage to display vertex colors though?

**Comment by gonzalocasas** [comment]
Nice! 👏 
Can we merge?

**Comment by tomvanmele** [comment]
@gonzalocasas entirely up to you...

**Pull request merged**
