### PR TITLE
Fix VolMesh delete cell

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
@gonzalocasas needs a test and docs but perhaps you can already give this a try...

**Comment by tomvanmele** [comment]
```python
from compas.datastructures import VolMesh

volmesh = VolMesh.from_meshgrid(9, 9, 9, 2, 1, 1)

print(volmesh)
print(volmesh._plane)

volmesh.delete_cell(0)

print(volmesh)
print(volmesh._plane)

```

**Comment by gonzalocasas** [comment]
Awesome, will review later today!

**Comment by gonzalocasas** [comment]
I tried this, but it still fails with a `KeyError`. Even the most minimal one:
```python
from compas.datastructures import VolMesh
volmesh = VolMesh.from_meshgrid()
volmesh.delete_cell(0)
```

**Comment by tomvanmele** [comment]
weird, for me that works perfectly

```python
from compas.datastructures import VolMesh

volmesh = VolMesh.from_meshgrid()

print(volmesh)
volmesh.delete_cell(0)
print(volmesh)
```

produces

```
<VolMesh with 1331 vertices, 3300 faces, 1000 cells, 3630 edges>
<VolMesh with 1331 vertices, 3297 faces, 999 cells, 3627 edges>
```

**Comment by tomvanmele** [comment]
@gonzalocasas please recheck because this is supposed to be fixed

**Review by gonzalocasas — APPROVED** [review]
LGTM! Thanks!!

**Pull request merged**
