### PR TITLE
pin sphinx extensions that work with sphinx 4.5

### PR DESCRIPTION
**Pull request by gonzalocasas**
https://stackoverflow.com/questions/77848565/sphinxcontrib-applehelp-breaking-sphinx-builds-with-sphinx-version-less-than-5-0

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tomvanmele — COMMENTED** [review]
why is this necessary? we don't use any of these extensions...

**Comment by gonzalocasas** [comment]
> why is this necessary? we don't use any of these extensions...

I chased down the reasons for this and it's not clear why or when this happened. These extensions are dependencies of sphinx it seems, but according to the [stackoverflow post above](https://stackoverflow.com/questions/77848565/sphinxcontrib-applehelp-breaking-sphinx-builds-with-sphinx-version-less-than-5-0), they haven't documented properly when these dependencies changed.

**Comment by jf---** [comment]
@gonzalocasas seems little harm in merging this PR ( perhaps squashing the nr of commits? )

**Comment by tomvanmele** [comment]
@gonzalocasas is this still relevant?

**Comment by gonzalocasas** [comment]
This is not needed anymore.

**Pull request closed without merging**
