### PR TITLE
Fix target generator exhaustion in iterable_like()

### PR DESCRIPTION
**Pull request by arpastrana**
### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [x] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).
1. [x] If you add new functions/classes, check that:
   1. [x] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [x] Add unit tests (especially important for algorithm implementations).

### Description

This is a bug fix to #367.  
Zipped values from `zip_longest` are computed and yielded one by one until `target` is exhausted.

Passing a `generator` as `target` will raise a `StopIteration` exception prematurely since `zip_longest` would have already consumed it. Therefore, `itertools.tee()` is introduced to create a `counter` upon which zipped values will be released.

We iterate over `counter`, (previously `target`), to also cap `reference` to the size of `target` in case the former is target than the latter. 

Default parameters have also been adjusted.

### How to reproduce?

This works (list and tuple):

```
import compas
from compas.utilities import iterable_like

keys = [0, 1, 2, 3]
color = (255, 0, 0)
f = list(iterable_like(keys, color))
print(len(keys) == len(f))  # True
```

This will not (generator and generator):

```
import compas

from compas.datastructures import Mesh
from compas.utilities import iterable_like

faces = Mesh.from_obj(compas.get("faces.obj"))
hypar = Mesh.from_obj(compas.get("hypar.obj"))

f = list(iterable_like(faces.faces(), hypar.faces(), as_single=False))
print(len(list(faces.faces())) == len(f))  # False
```

### CODE REVIEW

**Comment by tomvanmele** [comment]
would it make sense to drop the `as_single` parameter and leave it up to the user to wrap the reference value if it is supposed to be seen as a "single" value?

```python
colors = iterable_like(keys, [(255, 0, 0)])
```

**Comment by arpastrana** [comment]
It definitely makes it more succinct.

I have the impression though that `fillvalue` would need to always be explicitly defined since `reference` could thus be any iterable.

```
color = (255, 0, 0)
colors = iterable_like(keys, [color], color)
```

Would this look reasonable to you?

**Comment by tomvanmele** [comment]
it makes everything more explicit, which is a good idea i think...

**Comment by arpastrana** [comment]
`as_single` has been removed; dependant functions modified accordingly 😄

**Pull request merged**
