### PR TITLE
Fix install

### PR DESCRIPTION
**Pull request by gonzalocasas**
Make sure we clean up all remains of legacy installs when we re-install and uninstall.

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by beverlylytle** [comment]
WOMM!

**Comment by gonzalocasas** [comment]
@beverlylytle thx!

**Comment by tomvanmele** [comment]
what is "WOMM" tried looking it up but i get "word of mouth marketing" :)
works on my machine?

**Comment by gonzalocasas** [comment]
> works on my machine?

exactly!

image

**Pull request merged**
