### PR TITLE
Updated examples to work with current version of Compas

### PR DESCRIPTION
**Pull request by tetov**
* `delaunay_from_points` moved to `compas.geometry`
* `mesh_draw` replaced with `compas_rhino.Artists.MeshArtist`
* `mesh_from_guid` moved to `compas_rhino.helpers`
* changed order of arguments for `compas.geometry.rotate_points`

### What type of change is this?

Only touches docs.

### Checklist

1. [x] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).

### CODE REVIEW

**Comment by tetov** [comment]
Updated tutorial/callbacks as well, closing https://github.com/compas-dev/compas/issues/345.

**Comment by tomvanmele** [comment]
shall i merge?

**Comment by tetov** [comment]
Yes please, done for now :)

**Comment by tetov** [comment]
@brgcode: I’m sorry but could you please revert the merge or delete the file read_file.py in commit 97d29e1?

Was a bit too quick with the last commit. I also realized that I should probably squash my commits to not make history cluttered.

**Comment by gonzalocasas** [comment]
@tetov done! removed at https://github.com/compas-dev/compas/commit/15d036ef294a2da462568fca4d3e30472485f4c7

**Pull request merged**
