### PR TITLE
Changes to draw_breps() to fix #854 #855

### LINKED ISSUE #854: Expose draw_breps() at compas_rhino.utilities level and in documentation
I discovered this function that seems to work perfectly fine, although it is not used anywhere else in the core library. 
But I realize it is not in the `__all__` list. 

I want to ask if this function is intended to continue to exist in the future? And if so, can this be included in the `__all__` list

https://github.com/compas-dev/compas/blob/d2ba3a237a548b6bd396cc00913cae03a7189044/src/compas_rhino/utilities/drawing.py#L423-L511

### LINKED ISSUE #855: Adding function to join the breps when calling draw_breps()
# Feature Request

As a [user who build my own RhinoArtist for my custom geometry classes], I want [to create polysurfaces/joinnedBreps using the draw_breps() function] so that [benefit].

## Details

**Is your feature request related to a problem? Please describe.**
Calling `compas_rhino.utilities.drawing.draw_breps()` with a list of input results in drawing multiple Breps. I want an option to create the the individual faces, join them, add them to doc and return the joined brep(s) guids.

**Describe the solution you'd like**
I think this can be backward compatible by using a flag.

### PR DESCRIPTION
**Pull request by yck011522**
Fix #854 
Fix #855 

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [x] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tomvanmele — DISMISSED** [review]

**Comment by yck011522** [comment]
premature?

**Comment by tomvanmele** [comment]
there is something odd with the function itself that i need to look at first

**Comment by tomvanmele** [comment]
@yck011522 does the function work for you? seems odd that in the case of `p==4` we draw a triangle and in the case of `p==5` we draw a quad...

**Comment by yck011522** [comment]
Yes, this function works for me rather well.
I think the `p=4` case is for a triangle (end point counts double). Therefor `p=5` is a quad.

**Comment by tomvanmele** [comment]
but that's exactly what makes no sense. you shouldn't have to artificially double the last point in the face (like in your example) because it is never used except for the weird point count. wouldn't this make more sense?

```python
>>> from compas.datastructures import Mesh
>>> from compas.geometry import Box, Frame
>>> from compas_rhino.utilities import draw_breps
>>> box = Box(Frame.worldXY(), 1.0, 2.0, 3.0)
>>> mesh = Mesh.from_shape(box)
>>> breps = [{'points': mesh.face_coordinates(face)} for face in mesh.faces()]
>>> guids = draw_breps(breps, join=True)
```
with `p==3` for triangles and `p==4` for quads?

**Review by tomvanmele — APPROVED** [review]

**Comment by yck011522** [comment]
Oh. Okay. Sorry for the late reply, but yes, it makes more sense if the user just simply gives 4 points for a 4 cornered face. etc etc

**Pull request merged**
