### PR TITLE
test docs

### PR DESCRIPTION
**Pull request by Licini**
Adding test docs to CI:
https://github.com/compas-dev/compas-actions.docs/pull/1

### CODE REVIEW

**Review by tomvanmele — APPROVED** [review]
LGTM

**Comment by gonzalocasas** [comment]
interesting, some of the tests fail because they are not cross-platform basically (numpy-related data types change for example, I guess due to the target architecture of the running system). I would suggest we remove the `type` checking tests in `matrices.py`, they are not really checking much tbh. The other two failing tests are a numerical rounding one, we can use `allclose` instead, and a timing one with RPC which is a bit trickier to solve consistently, maybe we should skip it because we also have a unit tests for that anyway.

And a side note: maybe we should move the doctest before the docs are build, because building them takes forever, but testing them is faster, so if that fails, we save some lost cycles.

```
_____ [doctest] compas.datastructures.mesh.matrices.mesh_adjacency_matrix ______
050     Examples
051     --------
052     >>> from compas.datastructures import Mesh
053     >>> mesh = Mesh.from_polyhedron(6)
054     >>> A = mesh_adjacency_matrix(mesh)
055     >>> type(A)
056     <class 'numpy.ndarray'>
057 
058     >>> A = mesh_adjacency_matrix(mesh, rtype='csr')
059     >>> type(A)
Expected:
    <class 'scipy.sparse.csr.csr_matrix'>
Got:
    <class 'scipy.sparse._csr.csr_matrix'>

/home/runner/work/compas/compas/src/compas/datastructures/mesh/matrices.py:59: DocTestFailure
____ [doctest] compas.datastructures.mesh.matrices.mesh_connectivity_matrix ____
083     Examples
084     --------
085     >>> from compas.datastructures import Mesh
086     >>> mesh = Mesh.from_polyhedron(6)
087     >>> C = mesh_connectivity_matrix(mesh)
088     >>> type(C)
089     <class 'numpy.ndarray'>
090 
091     >>> C = mesh_connectivity_matrix(mesh, rtype='csr')
092     >>> type(C)
Expected:
    <class 'scipy.sparse.csr.csr_matrix'>
Got:
    <class 'scipy.sparse._csr.csr_matrix'>

/home/runner/work/compas/compas/src/compas/datastructures/mesh/matrices.py:92: DocTestFailure
_______ [doctest] compas.datastructures.mesh.matrices.mesh_degree_matrix _______
120     Examples
121     --------
122     >>> from compas.datastructures import Mesh
123     >>> mesh = Mesh.from_polyhedron(6)
124     >>> D = mesh_degree_matrix(mesh)
125     >>> type(D)
126     <class 'numpy.ndarray'>
127 
128     >>> D = mesh_degree_matrix(mesh, rtype='csr')
129     >>> type(D)
Expected:
    <class 'scipy.sparse.csr.csr_matrix'>
Got:
    <class 'scipy.sparse._csr.csr_matrix'>

/home/runner/work/compas/compas/src/compas/datastructures/mesh/matrices.py:129: DocTestFailure
________ [doctest] compas.datastructures.mesh.matrices.mesh_face_matrix ________
175     Examples
176     --------
177     >>> from compas.datastructures import Mesh
178     >>> mesh = Mesh.from_polyhedron(6)
179     >>> F = mesh_face_matrix(mesh)
180     >>> type(F)
181     <class 'numpy.ndarray'>
182 
183     >>> F = mesh_face_matrix(mesh, rtype='csr')
184     >>> type(F)
Expected:
    <class 'scipy.sparse.csr.csr_matrix'>
Got:
    <class 'scipy.sparse._csr.csr_matrix'>

/home/runner/work/compas/compas/src/compas/datastructures/mesh/matrices.py:184: DocTestFailure
_____ [doctest] compas.datastructures.mesh.matrices.mesh_laplacian_matrix ______
241     Examples
242     --------
243     >>> from compas.datastructures import Mesh
244     >>> mesh = Mesh.from_polyhedron(6)
245     >>> L = mesh_laplacian_matrix(mesh, rtype='array')
246     >>> type(L)
247     <class 'numpy.ndarray'>
248 
249     >>> L = mesh_face_matrix(mesh, rtype='csr')
250     >>> type(L)
Expected:
    <class 'scipy.sparse.csr.csr_matrix'>
Got:
    <class 'scipy.sparse._csr.csr_matrix'>

/home/runner/work/compas/compas/src/compas/datastructures/mesh/matrices.py:250: DocTestFailure
____ [doctest] compas.geometry._core.distance.closest_points_in_cloud_numpy ____
602     Notes
603     -----
604     Items in cloud further from items in points than threshold return zero
605     distance and will affect the indices returned if not set suitably high.
606 
607     Examples
608     --------
609     >>> points = [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]]
610     >>> cloud = [[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0]]
611     >>> closest_points_in_cloud_numpy(points, cloud, distances=True)
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
    -(array([0, 1, 2, 3], dtype=int64), array([[0.        , 1.        , 1.41421356, 1.        ],
    +(array([0, 1, 2, 3]), array([[0.        , 1.        , 1.41421356, 1.        ],
            [1.        , 0.        , 1.        , 1.41421356],
            [1.41421356, 1.        , 0.        , 1.        ],

/home/runner/work/compas/compas/src/compas/geometry/_core/distance.py:611: DocTestFailure
____________________ [doctest] compas.numerical.linalg.dof _____________________
160     float
161         Condition number, if ``condition`` is ``True``.
162 
163     Notes
164     -----
165     The degrees-of-freedom are the number of columns and rows minus the rank.
166 
167     Examples
168     --------
169     >>> dof([[2, -1, 3], [1, 0, 1], [0, 2, -1], [1, 1, 4]], condition=True)
Expected:
    (0, 1, 5.073596551276727)
Got:
    (0, 1, 5.073596551276725)

/home/runner/work/compas/compas/src/compas/numerical/linalg.py:169: DocTestFailure
_______________________ [doctest] compas.rpc.proxy.Proxy _______________________
084 
085     If possible, the proxy will try to reconnect to an already existing service
086 
087     Examples
088     --------
089     Minimal example showing connection to the proxy server, and ensuring the
090     server is disposed after using it:
091 
092     >>> from compas.rpc import Proxy
093     >>> with Proxy('compas.numerical') as numerical:
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,5 @@
     Starting a new proxy server...
    +    99 attempts left.
    +    98 attempts left.
     New proxy server started.
     Stopping the server proxy.
```

**Comment by gonzalocasas** [comment]
https://github.com/compas-dev/compas-actions.docs/pull/2

**Review by gonzalocasas — APPROVED** [review]
@Licini tests are fixed, so LGTM!

**Pull request merged**
