### PR TITLE
make matrix math specific to 4x4 matrices

### PR DESCRIPTION
**Pull request by Licini**
Added 4x4 matrix specific functions (skipping dimension checks) to make transformation faster

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [ ] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).
1. [ ] If you add new functions/classes, check that:
   1. [x] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

### CODE REVIEW

**Comment by Licini** [comment]
Questions:

1. Should the 4x4 specific function added to basics (like how it is now in commit), or resides somewhere under transformations folder
2. Does the function need to be written down even more explicitly (right now only skipping shape check)

**Comment by gonzalocasas** [comment]
I am not sure if I understood what @brgcode meant on this one, my impression was that were were going to change all existing functions to work with 4x4 matrices, not add a new variant that works only with 4x4; but I might be wrong.

**Comment by tomvanmele** [comment]
no i meant to add versions of matrix functions that work specifically/only for 4x4 matrices. but not just remove the shape check. also write out the math to remove all loops and make them as fast as possible in pure python...

**Comment by tomvanmele** [comment]
`transpose_matrix4`
`multiply_matrices4`
`invert_matrix4`
`determinant_matrix4`

**Comment by Licini** [comment]
> `transpose_matrix4`
> `multiply_matrices4`
> `invert_matrix4`
> `determinant_matrix4`

That's sounds more right to me.....However I'm a tiny bit doubting on how much performance it could improve since those are very small loops. But let me write that out and do a bit benchmark, probably will also compare with numpy. Optimisation tasks are always so fascinating

**Comment by Licini** [comment]
So after a little benchmark:
1 million original matrix multiplications : ~13s
1 million new explicit matrix multiplication : ~5s
1 million Numpy matrix multiplication : ~0.8s

**Comment by tomvanmele** [comment]
we could add a C++ version using ctypes in the mix to see if that makes a big difference...

**Comment by gonzalocasas** [comment]
> we could add a C++ version using ctypes in the mix to see if that makes a big difference...

you mean, as a baseline benchmark? because I don't expect we'll do better than numpy on that..

In the meantime, I tried a few things:
1. Using a tuple instead of list of list for the pure python version
1. Running the same tests inside Rhino
1. Added a test using Rhino SDK as backend

My benchmark values are as follows:
- 1 million original matrix multiplications : ~25s
- 1 million new explicit matrix multiplication : ~8s
- 1 million Numpy matrix multiplication : ~1.2s
- 1 million new explicit matrix multiplication using *tuples*: ~5s
- 1 million Rhino SDK matrix multiplication: ~1.1s

So, imo, we should focus on numpy and C# as backends, and transparently select the right one based on the environment.

**Pull request closed without merging**
