### PR TITLE
Move doctests out of source

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gonzalocasas** [comment]
It looks good so far, but I'm not sure if you are still working on it and adding doctests one by one to the unit tests?

One thing thou: it is possible to run the doctests without this explicit file in `/tests/` using `pytest --doctest-modules ` and adding the `src` to `testpaths` in `setup.cfg`; but maybe you want explicit control of which ones to add so that we don't have to fix too much in one go?

**Comment by tomvanmele** [comment]
> It looks good so far, but I'm not sure if you are still working on it and adding doctests one by one to the unit tests?
> 
> One thing thou: it is possible to run the doctests without this explicit file in `/tests/` using `pytest --doctest-modules ` and adding the `src` to `testpaths` in `setup.cfg`; but maybe you want explicit control of which ones to add so that we don't have to fix too much in one go?

no will fix all in one go. so sounds good...

**Comment by tomvanmele** [comment]
should the `python_files` section then also include a pattern for regular python files?

**Comment by gonzalocasas** [comment]
> should the `python_files` section then also include a pattern for regular python files?

Not really, we use the (i think) default for `compas_fab`:
```
python_files =
    test_*.py
    *_test.py
    tests.py
```

**Comment by tomvanmele** [comment]
how do you exclude all the blender and rhino and ghpython files?

**Comment by tomvanmele** [comment]
i added a `conftest.py` for some more control...

all doctests now pass locally (one test fails on linux, don't know why), but not every function has a test, and some are not super meaningful.

@gonzalocasas could you have a look at the ones for `compas.robots` because there the outout was clearly written with a particular input in mind and it is not clear to me which one that is...

**Review by gonzalocasas — APPROVED** [review]
Kudos for the massive cleanup!! LGTM! 😎

**Comment by gonzalocasas** [comment]
@brgcode do you want to merge and I check the robots part in a separate PR? Or prefer to do it all in this?

**Comment by tomvanmele** [comment]
> @brgcode do you want to merge and I check the robots part in a separate PR? Or prefer to do it all in this?

sorry, saw this after i merged :)

**Pull request merged**
