### PR TITLE
Add Python 3.9 support

### PR DESCRIPTION
**Pull request by gonzalocasas**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gonzalocasas** [comment]
The conda side of things seems to be finally unblocked: https://github.com/conda-forge/compas-feedstock/pull/91

I added 3.9 to the build matrix, but maybe we should remove one of the other python versions otherwise we will eventually reach the limits of the free tier.

**Review by tomvanmele — APPROVED** [review]
LGTM

**Comment by tomvanmele** [comment]
> The conda side of things seems to be finally unblocked: [conda-forge/compas-feedstock#91](https://github.com/conda-forge/compas-feedstock/pull/91)
> 
> I added 3.9 to the build matrix, but maybe we should remove one of the other python versions otherwise we will eventually reach the limits of the free tier.

what are the limits of the free tier?

**Comment by gonzalocasas** [comment]
> what are the limits of the free tier?

Sorry, I was confused. The limits apply only to private repositories, for open source, seems to be totally free:
image

**Pull request merged**
