### PR TITLE
BaseReader integrations: OBJ

### PR DESCRIPTION
**Pull request by tetov**
### What type of change is this?

- [x] New feature in a **backwards-compatible** manner.

### Checklist

1. [x] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).
1. [x] Add unit tests (especially important for algorithm implementations).

### Notes

First BaseReader integration and probably the easiest.

I've removed the line continuation check because I can't find any mention that in OBJ specifications.

I rewrote the previous line about BaseReader in CHANGELOG.md since it was based on the older PR that we decided to split up.

I've also added unittests. I decided to use files already present in `compas/data` and used in examples in documentation.

### CODE REVIEW

**Comment by tetov** [comment]
# Some notes on performance

I've done some profiling on two files. The first one is `lines_bigger.obj` found in `repo_root/data` which is 2.18 MB. The second is a very subdivided sphere I made for this test, it weighs in at 365 MB.
**EDIT:** Added a subdivided torus, 21.3 MB.

The main take away is that the new iter_lines()'s memory usage increases gradually as the OBJ object is populated with vertices and faces as we wanted. But the previous implementation is for the big obj-file.

The line tested is `obj = OBJ('path/to/file')`.

Run time from `compas.utilities.profiling` output.

Master's pre() and read() == PR's read() and _read_line() in terms of functionality.

## `lines_bigger.obj`
### source: master a1923fdce47e0d5c8b1be52b2a302d8ba10772a2
0.380 seconds
plot-master
```
running as a Python program...
         22576968 function calls in 15.990 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2088962    4.448    0.000    8.383    0.000 obj.py:207(_read_vertex_coordinates)
        1    4.423    4.423   15.990   15.990 obj.py:140(read)
  2088962    3.458    0.000    3.458    0.000 obj.py:216(<listcomp>)
  7084294    2.368    0.000    2.368    0.000 {method 'split' of 'str' objects}
    26265    0.486    0.000    0.788    0.000 obj.py:232(_read_polygonal_geometry)
  4995331    0.371    0.000    0.371    0.000 {method 'append' of 'list' objects}
  2115227    0.168    0.000    0.168    0.000 {built-in method builtins.len}
  2088962    0.137    0.000    0.137    0.000 obj.py:223(_read_vertex_texture)
  2088962    0.131    0.000    0.131    0.000 obj.py:226(_read_vertex_normal)
        1    0.000    0.000    0.000    0.000 obj.py:200(_read_comment)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### source: PR bbf4c8f0b122abc7446da26b071bbdd59e60e69b
0.374 seconds
plot-non-regex
```
running as a Python program...
         66891000 function calls (66890989 primitive calls) in 32.126 seconds

   Ordered by: internal time
   List reduced from 90 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  6293152    8.476    0.000   19.076    0.000 obj.py:166(_read_line)
        1    5.962    5.962   32.126   32.126 obj.py:102(read)
  2088962    4.525    0.000    4.525    0.000 obj.py:228(<listcomp>)
  6653584    3.445    0.000    4.457    0.000 base_reader.py:137(iter_lines)
  6293153    2.127    0.000    2.127    0.000 {method 'split' of 'str' objects}
  2088962    2.000    0.000    7.041    0.000 obj.py:219(_read_vertex_coordinates)
  6653584    1.419    0.000    5.876    0.000 {built-in method builtins.next}
  6293153    1.061    0.000    1.061    0.000 {method 'startswith' of 'str' objects}
  6653583    0.831    0.000    0.831    0.000 {method 'rstrip' of 'str' objects}
8382149/8382147    0.693    0.000    0.693    0.000 {built-in method builtins.len}
  6653583    0.641    0.000    0.641    0.000 {method 'strip' of 'str' objects}
  4538401    0.383    0.000    0.383    0.000 {method 'append' of 'list' objects}
  2088962    0.187    0.000    0.187    0.000 obj.py:235(_read_vertex_texture)
  2088962    0.183    0.000    0.183    0.000 obj.py:238(_read_vertex_normal)
    46846    0.102    0.000    0.102    0.000 {built-in method _codecs.utf_8_decode}
    46846    0.079    0.000    0.181    0.000 codecs.py:318(decode)
    26266    0.010    0.000    0.010    0.000 {method 'join' of 'str' objects}
      2/1    0.000    0.000    0.000    0.000 sre_parse.py:470(_parse)
      261    0.000    0.000    0.000    0.000 sre_parse.py:232(__next)
      259    0.000    0.000    0.000    0.000 sre_parse.py:253(get)
```


## `365 MB sphere`
### source: master a1923fdce47e0d5c8b1be52b2a302d8ba10772a2
15.990 seconds
plot-master
```
running as a Python program...
         22576968 function calls in 26.591 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2088962    7.902    0.000   14.667    0.000 obj.py:206(_read_vertex_coordinates)
        1    7.336    7.336   26.591   26.591 obj.py:139(read)
  2088962    5.898    0.000    5.898    0.000 obj.py:215(<listcomp>)
  7084294    3.519    0.000    3.519    0.000 {method 'split' of 'str' objects}
    26265    0.619    0.000    0.989    0.000 obj.py:231(_read_polygonal_geometry)
  4995331    0.616    0.000    0.616    0.000 {method 'append' of 'list' objects}
  2115227    0.331    0.000    0.331    0.000 {built-in method builtins.len}
  2088962    0.187    0.000    0.187    0.000 obj.py:222(_read_vertex_texture)
  2088962    0.183    0.000    0.183    0.000 obj.py:225(_read_vertex_normal)
        1    0.000    0.000    0.000    0.000 obj.py:199(_read_comment)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### source: PR bbf4c8f0b122abc7446da26b071bbdd59e60e69b
32.126 seconds
plot-non-regex
```
running as a Python program...
         69272060 function calls in 43.367 seconds

   Ordered by: internal time
   List reduced from 49 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  6293152   11.350    0.000   25.366    0.000 obj.py:135(_read_line)
        1    8.441    8.441   43.367   43.367 obj.py:100(read)
  2088962    5.132    0.000    5.132    0.000 obj.py:199(<listcomp>)
  6653584    4.813    0.000    6.165    0.000 base_reader.py:137(iter_lines)
  7444725    3.123    0.000    3.123    0.000 {method 'split' of 'str' objects}
  2088962    2.353    0.000    8.062    0.000 obj.py:190(_read_vertex_coordinates)
  6653584    1.907    0.000    8.072    0.000 {built-in method builtins.next}
  6293153    1.393    0.000    1.393    0.000 {method 'startswith' of 'str' objects}
  6653583    1.054    0.000    1.054    0.000 {method 'rstrip' of 'str' objects}
  8408382    0.855    0.000    0.855    0.000 {built-in method builtins.len}
    26265    0.806    0.000    1.264    0.000 obj.py:215(_read_polygonal_geometry)
  6653583    0.774    0.000    0.774    0.000 {method 'strip' of 'str' objects}
  5716200    0.525    0.000    0.525    0.000 {method 'append' of 'list' objects}
  2088962    0.286    0.000    0.286    0.000 obj.py:206(_read_vertex_texture)
  2088962    0.244    0.000    0.244    0.000 obj.py:209(_read_vertex_normal)
    46846    0.181    0.000    0.181    0.000 {built-in method _codecs.utf_8_decode}
    46846    0.118    0.000    0.299    0.000 codecs.py:318(decode)
    26266    0.015    0.000    0.015    0.000 {method 'join' of 'str' objects}
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
        1    0.000    0.000    0.000    0.000 base_reader.py:34(location)
```

## `21.3 MB torus`
### source: master a1923fdce47e0d5c8b1be52b2a302d8ba10772a2
1.238 seconds
plot-master
```
running as a Python program...
         1640372 function calls in 1.238 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.319    0.319    1.238    1.238 obj.py:139(read)
   574363    0.234    0.000    0.234    0.000 {method 'split' of 'str' objects}
   102400    0.218    0.000    0.218    0.000 obj.py:215(<listcomp>)
    41022    0.215    0.000    0.334    0.000 obj.py:231(_read_polygonal_geometry)
   102400    0.179    0.000    0.425    0.000 obj.py:206(_read_vertex_coordinates)
   471962    0.043    0.000    0.043    0.000 {method 'append' of 'list' objects}
   143422    0.014    0.000    0.014    0.000 {built-in method builtins.len}
   102400    0.008    0.000    0.008    0.000 obj.py:222(_read_vertex_texture)
   102400    0.008    0.000    0.008    0.000 obj.py:225(_read_vertex_normal)
        1    0.000    0.000    0.000    0.000 obj.py:199(_read_comment)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### source: PR bbf4c8f0b122abc7446da26b071bbdd59e60e69b
2.818 seconds
plot-branch
```
running as a Python program...
         4436062 function calls in 2.818 seconds

   Ordered by: internal time
   List reduced from 49 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   348223    0.597    0.000    1.758    0.000 obj.py:135(_read_line)
        1    0.489    0.489    2.818    2.818 obj.py:100(read)
   102400    0.305    0.000    0.305    0.000 obj.py:199(<listcomp>)
   392895    0.279    0.000    0.358    0.000 base_reader.py:137(iter_lines)
    41022    0.258    0.000    0.397    0.000 obj.py:215(_read_polygonal_geometry)
   619034    0.258    0.000    0.258    0.000 {method 'split' of 'str' objects}
   102400    0.172    0.000    0.516    0.000 obj.py:190(_read_vertex_coordinates)
   392895    0.116    0.000    0.473    0.000 {built-in method builtins.next}
   348224    0.072    0.000    0.072    0.000 {method 'startswith' of 'str' objects}
   561311    0.065    0.000    0.065    0.000 {method 'append' of 'list' objects}
   392894    0.062    0.000    0.062    0.000 {method 'rstrip' of 'str' objects}
   491648    0.052    0.000    0.052    0.000 {built-in method builtins.len}
   392894    0.045    0.000    0.045    0.000 {method 'strip' of 'str' objects}
   102400    0.011    0.000    0.011    0.000 obj.py:209(_read_vertex_normal)
   102400    0.011    0.000    0.011    0.000 obj.py:206(_read_vertex_texture)
    39915    0.010    0.000    0.010    0.000 {method 'join' of 'str' objects}
     2732    0.009    0.000    0.009    0.000 {built-in method _codecs.utf_8_decode}
     2732    0.007    0.000    0.016    0.000 codecs.py:318(decode)
        1    0.000    0.000    0.000    0.000 {built-in method posix.open}
        1    0.000    0.000    0.000    0.000 {built-in method io.open}
```

## Side note
I also created a implementation using a compiled regex. The run time increased to 1.352 for `lines_bigger.obj` and to 157.845 seconds for the 365 MB file. The increase is nearly all of it concentrated to the re.search() call.

I'll run some more test for a medium sized file and add them to this comment tomorrow.

**Comment by tomvanmele** [comment]
would be interesting to know where time is spent. is this just for reading or also parsing? could you add the profile output?

**Comment by tetov** [comment]
> would be interesting to know where time is spent. is this just for reading or also parsing?

The line tested is `obj = OBJ('path/to/file')`, so parsing should be included. I decorated the read() functions with `@profiling.print_profile`. Would you like me to limit the scope to only OBJReader?

> could you add the profile output?

I've updated the comment above. I had lost the the output for the large file so reran that, that's why the times don't match up.

Master's `pre()` and `read()` `==` PR's `read()` and `_read_line()` in terms of functionality.

**Comment by tetov** [comment]
Set this to WIP since it needs a to be merged with changes on master, and #529 should be fixed as well.

**Pull request closed without merging**
