### PR TITLE
Returns and Raises added to mesh_split_face docstring

### PR DESCRIPTION
**Pull request by tetov**
### What type of change is this?

Doc update

### Checklist

- ~~I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).~~
- ~~I ran all tests on my computer and it's all green (i.e. `invoke test`).~~
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- ~~I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.~~
- ~~I have added tests that prove my fix is effective or that my feature works.~~
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tetov** [comment]
Tried to write a doctest too but it's a bit tricky since the funcs in this module are only(?) meant to be used as an method to Mesh.

**Comment by tomvanmele** [comment]
the functions are indeed meant to take a mesh as first parameter. other than that they can perfectly be used as standalone functions. in fact, binding them to the mesh class is only a fairly recent change...

**Comment by tetov** [comment]
@brgcode: Ok, added an example and some unit tests.

**Comment by tomvanmele** [comment]
cool thanks

**Pull request merged**
