### PR TITLE
Add support for copy and pickle to artists

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gonzalocasas** [comment]
In terms of code, this looks good but i don't understand the context in which this is useful. In principle it even sounds counter intuitive to have serializable components in charge of visualization, and it adds additional requirements to implement new artists, but i guess there's a good use case for it. Could you add a couple of details about the situation in which you use this?

**Comment by tomvanmele** [comment]
we use this for serializing the state of an app, like FormFinder or RV2, such that it can be reloaded at a later point in time. artists and objects can have many settings that are a bit painful to serialize in any other way. the copy and deepcopy interface allow various independent states of live objects to be stored for undo/redo...

we tried to be more precise with the serialization by using a similar infrastructure as for the data classes, but it is difficult to get it right, whereas `pickle` and `shelve` provide this functionality out of the box.

```python
import time
import compas
import compas_rhino
from compas.datastructures import Mesh
from compas.geometry import Point
from compas_ui.app import App

compas_rhino.clear()

app = App(name='Test')
app.scene.clear()

mesh = Mesh.from_obj(compas.get('tubemesh.obj'))
mesh.name = 'TubeMesh'

obj = app.scene.add(mesh)
app.scene.update()
app.record()

time.sleep(1)

x, y, z = mesh.centroid()
obj.location = Point(-x, -y, 0)
app.scene.update()
app.record()

time.sleep(1)

app.undo()

app.save()
```

in the above, the scene creates UI objects and artists on the fly, which can have all sorts of settings that are object specific. keeping track of those states is difficult through, for example, the data mechanism...

**Comment by tomvanmele** [comment]
i can add this behaviour in `compas_ui` specifically if that is preferred

**Review by Licini — APPROVED** [review]
Looks good to me!

**Comment by tomvanmele** [comment]
gonna try this with a mixin in `compas_ui` first, we can see where to take it from there afterwards...

**Comment by tomvanmele** [comment]
works with a mixin in `compas_ui` so we can use it locally there for now. the other changes are still relevant though...

**Pull request closed without merging**
