### PR TITLE
Scenes

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [x] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
```python
from random import random
from compas.geometry import Pointcloud, Box, Frame
from compas.utilities import i_to_rgb
from compas.datastructures import Mesh

import compas_rhino
from compas_rhino.scene import Scene

compas_rhino.clear()

scene = Scene()

cloud = Pointcloud.from_bounds(10, 5, 3, 50)

for point in cloud:
    box = Box(Frame.worldXY(), random(), random(), random())
    box.frame.point = point
    mesh = Mesh.from_shape(box)
    color = i_to_rgb(random())
    scene.add(mesh, settings={'color.faces': color, 'color.vertices': color, 'color.edges': color})

scene.update()
```

**Comment by tomvanmele** [comment]
normal use of artists is also still possible of course

```python
from random import random
from compas.geometry import Pointcloud, Box, Frame
from compas.utilities import i_to_rgb
from compas.datastructures import Mesh

import compas_rhino
from compas_rhino.artists import MeshArtist

compas_rhino.clear()

cloud = Pointcloud.from_bounds(10, 5, 3, 50)

for point in cloud:
    box = Box(Frame.worldXY(), random(), random(), random())
    box.frame.point = point
    mesh = Mesh.from_shape(box)
    color = i_to_rgb(random())
    artist = MeshArtist(mesh)
    artist.draw_vertices(color=color)
    artist.draw_edges(color=color)
    artist.draw_faces(color=color)

compas_rhino.redraw()
```

**Comment by tomvanmele** [comment]
ping pong. would be cool if you could start reviewing this. would like to push this through this week and have the feeling some back and forth will be necessary...

**Comment by gonzalocasas** [comment]
I have some questions about naming and maybe the request to add also Blender's `Scene` object as well (as a way of testing the validity of some implementation assumptions made for Rhino). However, I have not had time to look into this in detail yet, and realistically, that will only happen towards the end of the week, so, if possible, I would ask you to hold the merge until then, and probably until early next week.

**Comment by tomvanmele** [comment]
no worries. will still have to push quite a few updates indeed. just wanted to get things started...

**Pull request closed without merging**
