### PR TITLE
Check API doc completeness

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
@Licini this works locally but fails online. any ideas?

**Comment by beverlylytle** [comment]
About the failing workflows, it looks like the folder `docs/api/generated` in the api test doesn't exist yet as the docs haven't been generated in the "build" workflow.  Maybe "compas-dev/compas-actions.docs" needs to be included in the build workflow, but that would slow things down quite a lot.

**Comment by Licini** [comment]
> @Licini this works locally but fails online. any ideas?

@beverlylytle was right about it

**Comment by Licini** [comment]
perhaps we can make this a separate test, seems this particular one dose not need to be tested in the matrix of platforms?

**Comment by brgcode** [comment]
a separate API test/workflow would make sense indeed. @Licini could you add something along those lines?

**Comment by tomvanmele** [comment]
in addition, we don't need to generate the complete docs for this. we just need the auto generated stubs. those can also be generated with 
```bash
sphinx-autogen docs/api/compas.**.rst -o temp/stubs
```

**Comment by tomvanmele** [comment]
@Licini i think it is working now, but could you still make a separate workflow for this because it indeed only needs to be checked once. and not for the entire matrix...

**Comment by gonzalocasas** [comment]
@brgcode ah, i think the ironpython-testrunner is evaluating fixtures even before they are needed, so, to fix the build fail on ipy you probably need to skip (`if compas.IPY: return`) inside the fixtures as well.

**Pull request merged**
