### PR TITLE
box is now at origin

### PR DESCRIPTION
**Pull request by tomvanmele**
The box shape is inconsistent with other shapes. If it is defined by its properties, it is not located at the origin, and the local origin is not at the center of the box. This PR fixes that...

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [x] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [ ] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [ ] Run all tests on your computer (i.e. `invoke test`).
1. [ ] If you add new functions/classes, check that:
   1. [ ] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

### CODE REVIEW

**Comment by romanarust** [comment]
Yes, correct. I would go for centering in x and y, but not in z.

**Comment by romanarust** [comment]
Correct, it very much feels strange that the frame is in the center of box....

**Comment by tomvanmele** [comment]
i understand, but it is inconsistent with other shapes and that is arguably the most confusing. note that if you create the box from spatial geometric inputs it will still be located in relation to those inputs, but the origin of its frame is always at the centroid. this seems to make the most sense for applying transformations...

**Comment by worbit** [comment]
hi all
i can understand the reservations, but i still think this makes sense.

Screenshot 2019-11-29 at 15 05 42

note that also grasshopper (left) and rhino (right) put the gumball / transformation handle / plane in the centre of the box (after creation). creating a box from two opposite corner points also still works in compas!

**Comment by tomvanmele** [comment]
yes, so the methods `from_diagonal`, `from_corner_corner_height`, ... still place the box at the specified locations, but the local coordinate system is at the centroid such that transformations can be applied transparently...

**Comment by romanarust** [comment]
true, then let's leave it like that. but we should we then provide methods like `Box.bottom/top_frame` and `Cylinder.bottom/top_frame` for convenience?

**Pull request merged**
