### PR TITLE
Update the link for contributing

### PR DESCRIPTION
**Pull request by rjodon**
Redirects to devguide even if it is not complete. Better than a broken link.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [x] Other (e.g. doc update, configuration, etc)

### Checklist

Not relevant. Just a link update in readme

### CODE REVIEW

**Comment by tetov** [comment]
@brgcode Didn't you decide to use [CONTRIBUTING.md](https://github.com/compas-dev/compas/blob/master/CONTRIBUTING.md) instead? See #530.

**Comment by tomvanmele** [comment]
the link to devguide.html is correct

**Comment by rjodon** [comment]
@tetov 

> @brgcode Didn't you decide to use [CONTRIBUTING.md](https://github.com/compas-dev/compas/blob/master/CONTRIBUTING.md) instead? See #530.

I'd say it makes more sense to link to the website documentation. For each extension, we can link to the same place for the contribution rules.. It is also easier to maintain.  However, the file ` CONTRIBUTING.md` contains extra informations. The website is not finished yet.

**Comment by tetov** [comment]
Yeah sorry I must have missed something. CONTRIBUTING.md was read by sphinx earlier and was part of the website.

**Comment by tomvanmele** [comment]
the `CONTRIBUTING.md` file is primarily there because it is part of the community guidelines of github. for a while it was the only guide we had. this should now be resolved by providing proper instructions in the devguide, which is indeed still a work in progress. i am trying to complete the documentation by the end of next week...

**Comment by tetov** [comment]
Ok! Thanks for explaining!

**Pull request merged**
