### PR TITLE
Merge xfroms into transformations

### PR DESCRIPTION
**Pull request by Licini**
create transofrmations.helper_numpy, moved all imports out of functions to top
merge compas.geometry.xforms into compas.geometry.transformations
**TESTs are to be added in this request**

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [ ] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [x] Run all tests on your computer (i.e. `invoke test`).
1. [ ] If you add new functions/classes, check that:
   1. [x] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

### CODE REVIEW

**Comment by Licini** [comment]
Question for @brgcode :
For migrated functions do we delete them or add deprecation warnings and delete them in a future version?

**Comment by gonzalocasas** [comment]
@Licini i know this is a draft, but I would suggest the files are not re-created, but really moved. Otherwise we lose the git history on them. And regarding the compatibility question, the easiest on the user would be to add aliases on the old location, and add a deprecation warning on the `xforms` package's `__init__` file.

**Comment by Licini** [comment]
@gonzalocasas thanks, that indeed makes more sense. Just to make sure, you mean to move the files, and keep the `__init__` of xforms, just change it to import from new location (and add deprecation warning), right?

**Comment by gonzalocasas** [comment]
> @gonzalocasas thanks, that indeed makes more sense. Just to make sure, you mean to move the files, and keep the `__init__` of xforms, just change it to import from new location (and add deprecation warning), right?

exactly ;)

**Comment by Licini** [comment]
@gonzalocasas sounds good, gonna close this and make a new request

**Pull request closed without merging**
