### PR TITLE
Add creasing to catmull-clark

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
bit difficult to test, but works fine so far :)

Screenshot 2021-03-26 at 17 30 07

```python
from compas.geometry import Box
from compas.geometry import dot_vectors, Translation
from compas.datastructures import Mesh

from compas_view2.app import App

cage = Mesh.from_shape(Box.from_width_height_depth(1, 1, 1))
cage.update_default_edge_attributes({'crease': 0})

top = sorted(cage.faces(), key=lambda face: dot_vectors(cage.face_normal(face), [0, 0, 1]))[-1]
bottom = sorted(cage.faces(), key=lambda face: dot_vectors(cage.face_normal(face), [0, 0, -1]))[-1]

c0 = cage.copy()
c1 = c0.transformed(Translation.from_vector([1.5, 0, 0]))
c2 = c1.transformed(Translation.from_vector([1.5, 0, 0]))
c3 = c2.transformed(Translation.from_vector([1.5, 0, 0]))
c4 = c3.transformed(Translation.from_vector([1.5, 0, 0]))
c5 = c4.transformed(Translation.from_vector([1.5, 0, 0]))

c1.edges_attribute('crease', 1, keys=list(cage.face_halfedges(top)))
c1.edges_attribute('crease', 1, keys=list(cage.face_halfedges(bottom)))

c2.edges_attribute('crease', 2, keys=list(cage.face_halfedges(top)))
c2.edges_attribute('crease', 2, keys=list(cage.face_halfedges(bottom)))

c3.edges_attribute('crease', 3, keys=list(cage.face_halfedges(top)))
c3.edges_attribute('crease', 3, keys=list(cage.face_halfedges(bottom)))

c4.edges_attribute('crease', 4, keys=list(cage.face_halfedges(top)))
c4.edges_attribute('crease', 4, keys=list(cage.face_halfedges(bottom)))

c5.edges_attribute('crease', 5, keys=list(cage.face_halfedges(top)))
c5.edges_attribute('crease', 5, keys=list(cage.face_halfedges(bottom)))

s0 = c0.subdivide(k=5)
s1 = c1.subdivide(k=5)
s2 = c2.subdivide(k=5)
s3 = c3.subdivide(k=5)
s4 = c4.subdivide(k=5)
s5 = c5.subdivide(k=5)

viewer = App()

viewer.add(c0, show_faces=False, show_edges=True)
viewer.add(s0)

viewer.add(c1, show_faces=False, show_edges=True)
viewer.add(s1)

viewer.add(c2, show_faces=False, show_edges=True)
viewer.add(s2)

viewer.add(c3, show_faces=False, show_edges=True)
viewer.add(s3)

viewer.add(c4, show_faces=False, show_edges=True)
viewer.add(s4)

viewer.add(c5, show_faces=False, show_edges=True)
viewer.add(s5)

viewer.run()
```

**Review by gonzalocasas — CHANGES_REQUESTED** [review]
I think this would need some kind of documentation (e.g. documenting the option to have the `crease` attribute on edges directly in the docstrings, otherwise it's basically invisible to users.

Maybe add an example (like the one you have in the PR comments) but for Rhino or Blender, so that it doesn't need the `compas_view2`.

Also, changelog ;)

**Comment by tomvanmele** [comment]
i added an example to the docstring but w/o viz.
otherwise the doctest would break.

perhaps it should just be in a code block instead...

**Review by gonzalocasas — APPROVED** [review]
LGTM

**Pull request merged**
