### PR TITLE
Pylance support through type stubs

### LINKED ISSUE #621: compas imports - work with pylance intellisense
# Feature Request

[Pylance ](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)is a feature rich python language plugin for VSCode. It provide code analysis and [intellisense](https://code.visualstudio.com/docs/editor/intellisense). 

The intellisense function works with python default functions and types and almost all other libraries I used (such as numpy). However it does not work with compas.

I suspect this is caused by the 2-layer-deep import routing that compas uses. If I write the full path, or in fact keep the default full path that Pylance automatically creates, the intellisense works, See below where `intersection_line_plane` is yellow, that one works.

I think @Achillx has faced similar problem.

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
Adding type annotations will have to happen at some point anyway and it helps solve the PyLance problem (at least partially). There are however a few things to be aware of.

* Adding type annotations in a way that is compatible with Python 2.7 (Rhino) is more elegant with stub files than by adding them in code comments.
* Adding the stub files at the "second import level" helps strengthen the definition of an API.
* Currently "Goto Definition" in VS Code will only load the stub file and not the original source file.
* Auto-import on the other hand will still use the fully qualified path (so not the path defined in the API)
* There seems to be no way to automatically copy the docstring into the sub files in a way that PyLance can read and understand.

All of that to say that this is still very much a WIP PR...

**Comment by tomvanmele** [comment]
@yck011522

**Comment by yck011522** [comment]
@brgcode 
Thanks a lot for addressing byhe pylance problem together with the type annotation issue. I'll try it out later. 

May I ask from the developer's workflow, is the pyi file manually put together? In another words. When a function is added, a corresponding entry have to be added in the pyi file? Thanks.

**Comment by tomvanmele** [comment]
yes at the moment there doesn't seem to be a good way to autogenerate stub files with meaningful annotations. autogenerated files basically accept `Any` and return `Any`.

this will be a bit painful at first because we have to start from scratch.
however, adding the type annotations directly in the code or in stub files instead seems like the same amount of work.

also, currently the "second level" API has to be defined manually by listing API items in the `__all__` variables of the modules. so we just have to find a way to not have to do it twice...

**Comment by tomvanmele** [comment]
@gonzalocasas @beverlylytle this is now ready for review. not implemented for the cad packages yet though...

**Pull request closed without merging**
