### PR TITLE
Default to python and not pythonw because it is not automatically installed on Mac

### PR DESCRIPTION
**Pull request by tomvanmele**
…talled on Mac

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tetov** [comment]
Last night I was thinking of opening a issue about this since `pythonw.exe` is also missing on linux. Haha!

I'll test this out a bit too.

**Comment by gonzalocasas** [comment]
I'm not really sure, this is something that we have tested quite a bit now, changing it right before the release feels wrong. Is `pythonw` installed with `python.app` package?
Would it be safer (or possible) to try to detect if pythonw is installed and default to it and only default to python isle it's not detected?

**Comment by tomvanmele** [comment]
yes but then we have to make more changes. for example `PYTHON_DIRECTORY` would have to be populated with `os.getenv('CONDA_PREFIX')` if the bootstrapper is not available. otherwise it will default to the system python...

**Comment by gonzalocasas** [comment]
An alternative would be to default to `pythonw` on Windows only, and default to `python` for any other platform.

EDIT: the downside of using `python` on Windows is that a black window will pop up while the call is executing, which in the case of the RPC server is basically up until you close Rhino or explicitly shutdown the server.

**Comment by tomvanmele** [comment]
ok will push updates accordingly...

**Comment by tetov** [comment]
Now I can start proxy implicitly in WSL too.

[Example](https://github.com/gramaziokohler/compas_mobile_robot_reloc/blob/bump/tests/test_proxy.py)

**Review by gonzalocasas — APPROVED** [review]
LGTM!

**Pull request merged**
