### PR TITLE
Use a junction instead of a symbolic link

### PR DESCRIPTION
**Pull request by tomvanmele**
Supposedly, this solves the installation problem for people with minimal rights on their computers...

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tomvanmele** [comment]
the difference with a symbolic link is minimal, and in fact it might be the better choice, reading this...
https://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link

**Review by gonzalocasas — CHANGES_REQUESTED** [review]
I don't think this works for all our uses. In particular, we use symlinks to link ghuser components, and junctions only works with directories, so, it would fail in that one. If we want to change to junctions, we could change the install procedure of gh components to copy them instead of symlink them (there's no real reason to symlink those I think).

**Comment by tomvanmele** [comment]
something like this?

**Comment by tomvanmele** [comment]
@gonzalocasas ping

**Review by gonzalocasas — APPROVED** [review]
lgtm

**Comment by gonzalocasas** [comment]
Three small comments: 
1) there's some commented out code that could be deleted
2) this change causes the privilege elevation pop up to appear multiple times
3) the `install_userobjects` function was added later, so, `compas_fab` has an older implementation in which the same code is in that repo, so this change doesn't affect it. I will need to update that

**Pull request merged**
