### PR TITLE
Update `Box` transform

### PR DESCRIPTION
**Pull request by romanarust**
Small fix on box transform to apply `Scale` to its width, height, length.

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by beverlylytle** [comment]
I would have expected that `Box.transform` behaves this way already, that is, that the dimensions of the box change according to the scaling of the transformation.  Indeed, `Sphere.transform` both moves the center point and scales the radius.  However, `Cylinder.transform` does not scale the height or the radius of the object.  `Capsule.transform` is confusing, in that it transforms the defining line, but not the radius.  All I mean to say is, I think this is a good change for `Box`, but for the other shapes and primitives, the behavior of `transform` is not consistent, and this maybe should be discussed.

**Comment by tomvanmele** [comment]
just to add on to this, what happens if the transformation contains a shear and/or projection component?

**Comment by romanarust** [comment]
This problem applies both to `Shape` and `Primitive`. 
If a `Box` is projected or sheared, is it then still a `Box`? If a `Circle` is scaled non-uniformly, is it then still a `Circle`?
We could ignore such "distortions" and simply raise a warning...

**Comment by beverlylytle** [comment]
In the case of `Sphere`, the maximum of the scalars is applied to the radius...

**Comment by tomvanmele** [comment]
> We could ignore such "distortions" and simply raise a warning...

so we allow the user to do what they want but point out in the docs that distortions might occur?
i would be in favour of that because the alternative is to do a lot of expensive checks in the background for every transformation...

**Comment by tomvanmele** [comment]
what is the plan with this?

**Comment by gonzalocasas** [comment]
Let's merge this as is.

**Pull request merged**
