### PR TITLE
Transform collections

### PR DESCRIPTION
**Pull request by tomvanmele**
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.

### Checklist

1. [ ] Add the change to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading: `Added`, `Changed`, `Removed`.
1. [ ] Run all tests on your computer (i.e. `invoke test`).
1. [ ] If you add new functions/classes, check that:
   1. [ ] Are available on a second-level import, e.g. `compas.datastructures.Mesh`.
   1. [ ] Add unit tests (especially important for algorithm implementations).

### CODE REVIEW

**Comment by tomvanmele** [comment]
just want to confirm that this is what we were talking about before i do the others...

**Comment by tomvanmele** [comment]
was also wondering if it makes sense to make a `PrimitiveCollection`.

and if it is still necessary to convert coordinates to float in the background. py3 does float division anyway. and perhaps it should be anyway up to the user to take care of this...

will shave quite bit of the instantiation time of large collections of objects.

**Comment by gonzalocasas** [comment]
Looks good to me. 

About the name of these functions, are we set on `_collection`? There's a bit of room for misinterpretation because of the [`collections` module](https://docs.python.org/3.8/library/collections.html). Not sure of an alternative thou, maybe `transform_many`?

**Comment by tomvanmele** [comment]
borh shapely and matplotlib refer to "collections" of points. that is where i got rhis from. so it is not that odd ...

**Comment by romanarust** [comment]
Great! I am not sure about PrimitiveCollection though, seems a bit too much...

**Comment by tomvanmele** [comment]
left the name as is for now. let's see what happens...

**Pull request merged**
