### PR TITLE
Add json serialization GH components

### PR DESCRIPTION
**Pull request by gonzalocasas**
Add two components to serialize and deserialize `compas` objects to JSON string/files.
image

**NOTE:** We need proper icons for this, I used the generic `compas` icon for now, but we should change them before merging.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.md` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [ ] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke lint`).
- [ ] I added new functions/classes and made them available on a second-level import, e.g. `compas.datastructures.Mesh`.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by tomvanmele — APPROVED** [review]

**Comment by gonzalocasas** [comment]
@juney-lee would you have time to two icons for these components? Thanks!

**Comment by gonzalocasas** [comment]
naming question to all reviewers: `json_file_or_string` looks awful long, any suggestions? Should I instead name it `json` and also name `json` the output of the `ToJson` component so that they are symmetric?

**Comment by beverlylytle** [comment]
> Should I instead name it json and also name json the output of the ToJson component so that they are symmetric?

That sounds good.

**Comment by gonzalocasas** [comment]
image

**Pull request merged**
